### ISSUE TITLE
Убрать код Google Maps с ненужных страниц

### ISSUE THREAD

**Issue by olegpolyakov** [Alexzanderk/node-expert-vulkan#2]

**Comment by olegpolyakov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Выполнить ДЗ №2](https://trello.com/c/qJuOY3Tu/3-%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D1%8C-%D0%B4%D0%B7-%E2%84%962)

**Comment by Alexzanderk** [comment]
Код используется только в месте инициализации google maps.
